### ISSUE TITLE
Yomichan and Kiwi Browser Issue: Text Selection and Copying Problem

### ISSUE THREAD

**Issue by huannv100** [themoeway/yomitan#210]
I'm using Yomichan on the Kiwi browser with the Scan modifier key set to 'No key.' However, there appears to be an issue with the interaction between Yomichan and the browser, which is preventing me from selecting and copying text as I would normally do without using Yomichan. Is there a solution to this problem?

**Comment by fauu** [comment]
I'm not entirely sure but I believe the only way you can have working selection currently is to disable "Select matched text" in Scanning options. But the price you pay is losing the highlighting of the matched word. I'm still on a pre-fork version though, so it's possible that the information doesn't apply to this fork.

**Comment by huannv100** [comment]
Actually, I'm also using the pre-fork version. I tried disabling "Select matched text," but it still doesn't work. I cannot copy the selected words; it only works about 1 out of 20-30 tries, regardless of whether "Select matched text" is disabled or not.

**Comment by fauu** [comment]
I found something you could try: in "Scanning" go to "Configure advanced scanning inputs" and make sure "Mouse" is not selected and "Touch" is selected (and below that also "Scan on touch press").

**Comment by HuanNV9** [comment]
Thank you. 
I just tried, but it still doesn't work. Does it work on your end?

**Comment by fauu** [comment]
Yes, I get the Yomichan popup when I tap on a text and I get a normal text selection when I tap and hold on the text, with working copying and so on. I'm on Yomichan 22.10.23.0, Kiwi Browser 116.0.5845.72, Android 12.

Some other Yomichan settings that could be relevant: in "Configure advanced scanning inputs" I have just a single input defined. "Required inputs" and "Excluded inputs" are both empty, only the "Touch" input type is selected, and below that "Scan on touch press", "...move", "Prevent touch scrolling" are on. At the end of the "Scanning" section under "Support inputs for devices with touch screens", I have "Touch inputs" selected and "Pointer inputs" not selected.

**Comment by TheMadHau5** [comment]
I am on the same versions of Yomichan, Kiwi, and Android. I have changed my settings to match what you said, but the selection popup doesn't appear, only the Yomichan popup does. Any ideas?

**Comment by fauu** [comment]
I'm out of ideas for now. You could try the 10ten Japanese Reader extension instead of Yomichan and see if it works there. It has an option to look up words not by tapping them but by dragging a puck over them, which should interfere less with the normal text selection mechanism.

**Comment by huannv100** [comment]
Thank you. Unfortunately, I couldn't get it to work. Actually, I'm using Yomichan for Korean.

**Comment by Mansive** [comment]
Using these scanning options allows you to select text better at the cost of reintroducing accidental popups when swiping across pages. An alternative is to hold tap on special characters such as quotes or periods, then drag to select the actual text you want.
![image](https://github.com/themoeway/yomitan/assets/33560917/eb3a4587-c64f-434f-9273-0d5faae6a064)

**Comment by djahandarie** [comment]
@huannv100 Are you having the issue on the latest release of Yomitan? Did the above settings help you?

**Comment by huannv100** [comment]
The setting didn't help. I haven't tried Yomitan because I believe it doesn't currently support Korean.

**Comment by asodugf12** [comment]
I found a workaround to this issue. If you hold on letters that cannot be parsed by the dictionary, for example in japanese the small ya (ゃ), yo (ょ), yu (ゅ) and the small tsu (っ). Things like ちゃ, きゅ and った are great places for this.

**Comment by Kuuuube** [comment]
This should be fixed with the addition of touch tap touch option.

**Comment by huannv100** [comment]
I downloaded and installed Yomitan, but I still have the same issue with copying on the Kiwi browser. How should I set up the touch tap touch option?
