### ISSUE TITLE
Yomitan crashes on Google Chrome multiple times an hour

### ISSUE THREAD

**Issue by AdriGrana** [themoeway/yomitan#922]
**Description**
Yomitan crashes completely every 20 minutes or so (sometimes it doesn't for multiple hours, so it's really inconsistent). I cannot find any patterns to what else I am doing that would cause it, so it could well be that other extensions or programms would interfere since I did not have this issue in the past. I always have a Yomitan search window open, so not sure that has anything to do with it. Here the latest errors:

![image](https://github.com/themoeway/yomitan/assets/63470662/bccc0d85-c790-4834-839a-286341437e3a)
![image](https://github.com/themoeway/yomitan/assets/63470662/2954d177-858d-40b3-80d1-226e4100e2ac)
![image](https://github.com/themoeway/yomitan/assets/63470662/5c414eb7-ef72-4d98-bd6c-8cbc73abb1af)
![image](https://github.com/themoeway/yomitan/assets/63470662/48c06f3b-160e-4346-a5d5-6905c449b762)
![image](https://github.com/themoeway/yomitan/assets/63470662/76d39fff-2346-405a-8151-aa8e89f2e0f1)
![image](https://github.com/themoeway/yomitan/assets/63470662/abafc55c-4972-4320-bfd3-c04b7af2a54a)
![image](https://github.com/themoeway/yomitan/assets/63470662/5ccd086f-065e-49f0-95fd-b1208c279dd9)

If there is any more information you need please tell me and I shall provide it!

**System**
Windows 10
AMD Ryzen 7800X3D
Nvidia RTX4080
32GB RAM 5200MT/s (GDDR5)

**Browser version**
Chrome is up to date
Version 124.0.6367.202 (Official Build) (64-bit)

**Yomitan version**
Extension version: Yomitan 24.4.16.0

**Exported settings file**
[yomitan-settings-2024-05-12-19-20-32.json](https://github.com/themoeway/yomitan/files/15287399/yomitan-settings-2024-05-12-19-20-32.json)

**Comment by Kuuuube** [comment]
I suspect this is already fixed on master. There should be a new pre release put out soon you can test with.

But also try clearing the errors and then as soon as this happens send the errors. Chrome stores errors for a very long time so there's no guarantee most of those have anything to do with this issue.

**Comment by AdriGrana** [comment]
Thanks for the fast reply!

Great to hear that it should already be fixed, I'll test it out as soon as the pre-release is out and report back if it still persists!

**Comment by AdriGrana** [comment]
@Kuuuube It seems like even with the newest prereleas build (24.5.14.0) it still crashes pretty often. 

So to not waste anyones time, what would you or anyone else need to know to properly tell why it's crashing on my machine? Is there some guide I can walk through perhaps? 

I am good with technology and a programmer myelf but come from a completely different field than web applications, but if you tell me what I need to provide you, even if it is more techincal I think I can do that (just tell me the key stuff you need basically, the rest I can research and figure out myself and provide you). For example, could I somehow monitor Yomitan while it's running and log everything so you could exactly see where it fails?

I would appreciate any kind of help a lot!

**Comment by Kuuuube** [comment]
This may be due to manifest v3 and the newer rules around background services (the `Extension context invalidated` error is probably it dying).

I'm not exactly sure what is causing this or if theres a good solution to it but someone in the TMW discord server mentioned these steps a bit ago that could help:

Go to `chrome://extensions/`
Click the `service worker` link for Yomitan
You will need to keep this window opened and do this again every time you close the browser.

Since this seems to be something only few users are experiencing there may be some browser settings you've changed that makes cleaning up background services more aggressive. Not sure.

**Comment by AdriGrana** [comment]
Thanks for the very fast reply, really appreciate it!

Having the worker open also doesn't really solve this issue, it keeps crashing equally often. Anything else I can do one my side?
